services:
  - type: web
    name: bughive-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm run start
    region: oregon
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: "10000"

databases:
  - name: bughive-db
    dbName: bughive
    user: bughive_user
    region: oregon
